<?php

/**
view usada para gerar conteudo do fetchall em .CSV
*/
//CONFIGURACOES
$separador = ";";
$novalinha = "\n";
// FIM CONFIGURACOES
$competitionId = (isset($this->filter['competition_id']))? $this->filter['competition_id'] : $this->competitionId;

echo "Razão Social{$separador}CPF{$separador}Nome Fantasia{$separador}CNPJ{$separador}Email{$separador}UF{$separador}";

echo "Classificar Final{$separador}";
echo "Verificador{$separador}";
echo "Desclassificar{$separador}";
echo "Pontos Gerais{$separador}";
echo "Pontuação  Gestão{$separador}";
echo "Média Relato Avaliador{$separador}";
echo "Prêmio{$separador}";
echo "Critério de Avaliação{$separador}";

if ($competitionId == 2013) {
	echo "Pontos Empreendedorismo{$separador}";
}
echo $novalinha;

$i = 1;
if (count($this->getAllEnterprise) >= 1) :
   foreach ($this->getAllEnterprise as $enterprise) {
       
        $socialName = rr ( $enterprise->getSocialName() );
        $inscricaoEstadual = ''; //rr2 ( $enterprise->getInscricaoEstadual() );
        $fantasyName = rr ( $enterprise->getFantasyName() );
        $enterpriseTypeId = 2; //$enterprise->getEnterpriseTypeId();
        $CNPJ = trim($enterprise->getCnpj());
        $CPF = trim($enterprise->getCpfUser());
        $enterpriseType = ($enterpriseTypeId == '1')?$CNPJ:$CPF;
        $email = trim($enterprise->getEmailDefault());
        
        $getClassificado = ($enterprise->getClassificarNacional() == '1' )?'SIM':'NÃO';
        
        $getDesclassificarNacional = ($enterprise->getDesclassificarNacional() == '1' )?'SIM':'NÃO';
        $premio = str_replace('Microempreendedora', 'Microemp.', $enterprise->getDescriptionEca());
        
        $PontuacaoFinal = $enterprise->getPontosVerificador();
        if (isset($this->allCheckers)):
	        if(($score->count() > 0 and $score[0]->EnterpriseId == $enterpriseUserid) ){
	        	foreach ($this->allCheckers as $checker):
	        		$verificadorNome .= $checker->getFirstName() . ' ' . $checker->getSurname();
	        	endforeach;
        	}
        endif;
        
        
        
        $pontosGeral = (($enterprise->getPontosGeral() != null) ? $enterprise->getPontosGeral() : '--');
        $NotaAutoAvalVerificador  = $executionPontuacaoManager->calculateExecutionScore(52,$enterpriseUserid,true);
//         $qtPf = $enterprise->getQtdePontosFortes();
//                                 if ($qtPf === false) {
//                                     $bonus = '0';
//                                 } elseif ($qtPf >= 8) {
//                                     $bonus = '20%';
//                                 }  elseif ($qtPf >= 5) {
//                                     $bonus = '10%';
//                                 } else {
//                                     $bonus = '0';
//                                 }
//         $pontosNegocios = number_format($enterprise->getNegociosTotal()*10, 1 , ',', '.').'%';
        $mediaRelato = number_format($enterprise->getMediaPontos(), 1 , ',', '.');
        $QtdPontosFortes = $enterprise->getQtdePontosFortes();
        
        if($QtdPontosFortes == 0)   $QtdPontosFortes = 0;
        if($QtdPontosFortes == 1)   $QtdPontosFortes = 2;
        if($QtdPontosFortes == 2)   $QtdPontosFortes = 4;
        if($QtdPontosFortes == 3)   $QtdPontosFortes = 6;
        if($QtdPontosFortes == 4)   $QtdPontosFortes = 8;
        if($QtdPontosFortes == 5)   $QtdPontosFortes = 10;
        if($QtdPontosFortes == 6)   $QtdPontosFortes = 12;
        if($QtdPontosFortes == 7)   $QtdPontosFortes = 14;
        if($QtdPontosFortes == 8)   $QtdPontosFortes = 16;
        if($QtdPontosFortes == 9)   $QtdPontosFortes = 17;
        if($QtdPontosFortes == 10)  $QtdPontosFortes = 18;
        if($QtdPontosFortes == 11)  $QtdPontosFortes = 19;
        if($QtdPontosFortes == 12)  $QtdPontosFortes = 20;
        if ($competitionId == 2013) {
            $pontosEmpreende = number_format($enterprise->getPontosEmpreendedorismo(), 2 , ',', '.');
        }
        
        echo $socialName ? $socialName : $enterpriseType; //Razao Social
        echo $separador;
        echo $CPF.$separador;
        echo $fantasyName.$separador; //Nome Fantasia
        echo $CNPJ.$separador; //CPF/CNPJ
        echo $email.$separador;
        echo rr2($enterprise->getUf()).$separador;
        
        echo $getClassificado.$separador;
        echo $verificadorNome.$separador;
        echo $getDesclassificarNacional.$separador;
        
        echo number_format($PontuacaoFinal, 1 , ',', '.').$separador;
        echo number_format($NotaAutoAvalVerificador*1, 1 , ',', '.').$separador;
        echo number_format($mediaRelato, 1 , ',', '.').$separador;
        
        echo $premio.$separador;
        echo $QtdPontosFortes.separador;
        
        //echo $pontosNegocios.$separador;
        
        if ($competitionId == 2013) {
            echo $pontosEmpreende.$separador;
        }
        
//         echo number_format($pontosGeral*100, 1 , ',', '.') . '%'.$separador;
//         echo $bonus.$separador;
//         echo $mediaRelato.$separador;
                
        echo $novalinha; 
        $i = $i + 1;
   }
   
   echo $novalinha; 
   
endif;