<?php
$this->headScript()
    ->appendFile($this->baseUrl('js/management/appraiser/list.js?x1'))
;
?>
<table class="table">
  <caption></caption>
  <thead>
    <tr>
      <th style="position: relative">Empresa</th>
      <th>UF</th>
        <th>Ranking</th>
      <th class="appraisers-confirm">Vencedor<br>Nacional</th>
      <th>Prata</th>
      <th>Bronze</th>
      <th class="appraisers-cancel">Desclassificar</th>
      <th>Pontuação</br>Final</th>
	  <th>Nota <br>Verificador <br>Questionário <br>de Auto Aval.</br>Negócios</th>
	  <th>Nota <br>Verificador <br>Questionário <br>de Visita</th>
	  <th>Nota <br>Verificador <br>Critério <br>de Avaliação</th> 
      <th>Relat.<br>Interno</th>
      <th>Pontos<br>Negócios</th>
      <th>Prêmio</th>
      <?php if ($competitionId == '2013') : ?>
      <th>Pontos<br />Empreende.</th>
      <?php endif; ?>
      <th>RAA</th>
    </tr>
  </thead>
<?php if (count($this->getAllEnterprise) >= 1): ?>
  <tbody>
<?php

  foreach ($this->getAllEnterprise as $index => $enterprise):
  
  $QtdPontosFortes = 1; //$enterprise->getQtdePontosFortes();
  
  if($QtdPontosFortes == 0)   $QtdPontosFortes = '0';
  if($QtdPontosFortes == 1)   $QtdPontosFortes = '2';
  if($QtdPontosFortes == 2)   $QtdPontosFortes = '4';
  if($QtdPontosFortes == 3)   $QtdPontosFortes = '6';
  if($QtdPontosFortes == 4)   $QtdPontosFortes = '8';
  if($QtdPontosFortes == 5)   $QtdPontosFortes = '10';
  if($QtdPontosFortes == 6)   $QtdPontosFortes = '12';
  if($QtdPontosFortes == 7)   $QtdPontosFortes = '14';
  if($QtdPontosFortes == 8)   $QtdPontosFortes = '16';
  if($QtdPontosFortes == 9)   $QtdPontosFortes = '17';
  if($QtdPontosFortes == 10)  $QtdPontosFortes = '18';
  if($QtdPontosFortes == 11)  $QtdPontosFortes = '19';
  if($QtdPontosFortes == 12)  $QtdPontosFortes = '20';
  
  $NotaAutoAvalVerificador = 100;
  $NotaQuestVisitaVerificador = $this->getAllApeEvaluationVerificador2->getPontosFinal();
  
  $PontuacaoFinal =  (($NotaAutoAvalVerificador/5) + ($NotaQuestVisitaVerificador/1.66666) + $QtdPontosFortes);
    
    $raa = $enterprise->getDevolutivePath();
    $fantasyName = $enterprise->getFantasyName();
    $cnpj = trim($enterprise->getCnpj());
    $UF = trim($enterprise->getUf());

    $businessPoints = $enterprise->getNegociosTotal();
    $generalPoints = Model_Enterprise::getGeneralPointsFor($businessPoints, $enterprise->getStatusA4(),
      $enterprise->getPontosA4(), $enterprise->getStatusA5(), $enterprise->getPontosA5(), $enterprise->getStatusA6(),
      $enterprise->getPontosA6(), null
    );

    $verificadores = array(
      'confirm' => array(
        'status' => (($enterprise->getClassificadoOuroNacional() != null) ? $enterprise->getClassificadoOuroNacional() : false),
        'statusPrata' => (($enterprise->getClassificadoPrataNacional() != null) ? $enterprise->getClassificadoPrataNacional() : false),
        'statusBronze' => (($enterprise->getClassificadoBronzeNacional() != null) ? $enterprise->getClassificadoBronzeNacional() : false),
      ),
      'cancel' => array(
        'status' => (($enterprise->getDesclassificarFase2Nacional() != null) ? $enterprise->getDesclassificarFase2Nacional() : false),
        'note' => trim($enterprise->getMotivoDesclassificadoFase2Nacional())
      )
    );
?>
    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?> <?php echo ($verificadores['cancel']['status'] ? 'editable' : ''); ?>" data-idkey="<?php echo $enterprise->getIdKey(); ?>">
        <td style="position: relative">
            <dl style="text-align: left">
                <dt title="<?php echo $fantasyName ?>"><b><?php echo $fantasyName ?></b></dt>
                <dd class="identity" title="<?php echo $cnpj ?>"><?php echo $cnpj ?></dd>
            </dl>
        </td>

        <td class="middle"><i><?php echo $UF; ?></i></td>

        <td class="middle">
            <?php echo ($index+1) ?>
        </td>

        <td class="middle">
            <?php if ($generalPoints != '-'): ?>
              <input type="checkbox" 
                <?php if ($isCurrentCompetition) : ?>
                    name="change-ranking-<?php echo $index; ?>" id="change-ranking-<?php echo $index; ?>" class="change-ranking" value="1" 
                <?php else : ?> disabled <?php endif; ?>
               <?php echo ($verificadores['confirm']['status'] ? 'checked="checked"' : ''); ?> />
          <?php endif; ?>
        </td>
        <td class="middle">
            <input type="checkbox" 
                <?php if ($isCurrentCompetition) : ?>
                name="x" id="s2" class="change-ranking" value="2" 
                <?php else : ?> disabled <?php endif; ?>
            <?php echo ($verificadores['confirm']['statusPrata'] ? 'checked="checked"' : ''); ?> />
        </td>
        <td class="middle">
            <input type="checkbox" 
                <?php if ($isCurrentCompetition) : ?>
                name="x" id="s2" class="change-ranking" value="3" 
                <?php else : ?> disabled <?php endif; ?>
                <?php echo ($verificadores['confirm']['statusBronze'] ? 'checked="checked"' : ''); ?> />
        </td>
      <td class="middle">
        <input type="checkbox" 
               <?php if ($isCurrentCompetition) : ?>
               name="cancel-ranking-<?php echo $index; ?>" id="cancel-ranking-<?php echo $index; ?>" class="cancel-ranking" value="<?php echo $enterprise->getIdKey(); ?>" 
            <?php else : ?> disabled <?php endif; ?>
            <?php echo ($verificadores['cancel']['status'] ? 'checked="checked"' : ''); ?> />
        <a href="" title="Editar justificativa" class="cancel-ranking-note-edit">(editar justificativa)</a>
      </td>

<td class="middle">
	<dl>
		<dt>

          <?php            
             echo number_format($PontuacaoFinal, 1 , ',', '.');            
          ?>                 
        </dt>
	</dl>
</td>
<td class="middle">
	<dl>
		<dt>
        <?php 
        printf($NotaAutoAvalVerificador) ?>                    
        </dt>
	</dl>
</td>
<td class="middle">
	<dl>
		<dt>		
        <?php printf($NotaQuestVisitaVerificador) ?>                    
        </dt>
	</dl>
</td>
<td class="middle">
	<dl>
		<dt>
		<?php 
		
		?> 
         <?php if($enterprise->getQtdePontosFortes() == 0) echo '0'?>
         <?php if($enterprise->getQtdePontosFortes() == 1) echo '2'?>
         <?php if($enterprise->getQtdePontosFortes() == 2) echo '4'?>
         <?php if($enterprise->getQtdePontosFortes() == 3) echo '6'?>
         <?php if($enterprise->getQtdePontosFortes() == 4) echo '8'?>
         <?php if($enterprise->getQtdePontosFortes() == 5) echo '10'?>
         <?php if($enterprise->getQtdePontosFortes() == 6) echo '12'?>
         <?php if($enterprise->getQtdePontosFortes() == 7) echo '14'?>
         <?php if($enterprise->getQtdePontosFortes() == 8) echo '16'?>
         <?php if($enterprise->getQtdePontosFortes() == 9) echo '17'?>
         <?php if($enterprise->getQtdePontosFortes() == 10) echo '18'?>
         <?php if($enterprise->getQtdePontosFortes() == 11) echo '19'?>
         <?php if($enterprise->getQtdePontosFortes() == 12) echo '20'?>
        </dt>
	</dl>
</td>            
      <td class="middle" style="height: 43px;">
        <dl>
          <dt>
            <a href="<?php echo $this->baseUrl("management/appraiser/internal-report/enterprise-id-key/{$enterprise->getIdKey()}/competition-id/{$competitionId}"); ?>#report" target="_blank" title="Relatório Interno" class="download-raa" target="blank">Interno</a>
          </dt>
        </dl>
      </td>
 
      <td class="middle"><span>
          <?php
            echo number_format($businessPoints*10, 1 , ',', '.').'%';
            ?>
          </span></td>

        <td class="middle"><span><?php echo str_replace('Microempreendedora', 'Microemp.', $enterprise->getPremio()); ?></span></td>
        <?php if($competitionId == '2013') : ?>
        <td class="middle"><span><?php echo number_format($enterprise->getPontosEmpreendedorismo(), 2 , ',', '.');?></span></td>
        <?php endif; ?>
        <td class="middle">
          <dl>
              <dt>
                  <?php if ($raa): ?>
                      <a href="<?php echo $raa; ?>" title="Baixar RAA" class="report">Baixar RAA</a>
                  <?php endif; ?>
              </dt>

          </dl>
        </td>
    </tr>
    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="<?php echo $enterprise->getIdKey(); ?>">
      <td class="cancel-ranking-fieldset" data-saved="true">
        <dl>
          <dt><label>Justificativa <i>(obrigatório)</i></label></dt>
          <dd class="field"><textarea name="cancel-ranking-note-<?php echo $index; ?>" id="cancel-ranking-note-<?php echo $index; ?>" class="cancel-ranking-note"><?php echo $verificadores['cancel']['note']; ?></textarea></dd>
          <dd class="button"><a href="" title="Salvar" class="cancel-ranking-note-save">Salvar</a></dd>
          <!--a href="#" title="Fechar" onclick="console.log($(this).closest('td').hide());return false;">(X)</a-->
        </dl>
      </td>
    </tr>
<?php
  endforeach;
?>
  </tbody>
<?php
endif;
?>
</table>
