<div class="page-cronograma">
<h2>CRONOGRAMA</h2>
<h3>
    Sua trajetória pode abrir caminho<br>
    para milhares de outras mulheres
</h3>
<div class="box-cronograma cf">
    <div class="float--left">
        <table class="tbl-show">
            <tr>
                <td class="laranja" id="crono-principal">
                    <div style="position: relative;">
                        <div style="width: 200px; margin: 0 auto">
                            <strong id="showDia" class="showDia">08 março</strong>
                        </div>
                        <hr class="both">
                        <div id="showDescricao" style="margin: 0 auto; width: 190px">Início das candidaturas 2014</div>
                        <div id="crono-prev" class="crono-nav" title="Anterior">Anterior</div>
                        <div id="crono-next" class="crono-nav"  title="Próxima">Próxima</div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="float--left">
        <table class="tbl" id="table-datas">
            <tr>
                <td class="crono-date roxo" data-dia="08 março" data-descricao="Início das candidaturas 2014">08<br>março</td>
                <td class="crono-date roxo" data-dia="31 julho" data-descricao="Término das candidaturas">31<br>julho</td>
                <td class="crono-date roxo" data-dia="agosto/outubro" data-descricao="Avaliação e Visitas Etapa Estadual">agosto/<br>outubro</td>
            </tr>
            <tr>
                <td class="crono-date rosa" data-dia="outubro/fevereiro" data-descricao="Reconhecimento Estadual 2014">outubro/<br>fevereiro</td>
                <td class="crono-date rosa" data-dia="21 novembro" data-descricao="Envio da Documentação das Vencedoras a FNQ">21<br>novembro</td>
                <td class="crono-date cinza disable" data-dia="" data-descricao="">/</td>
            </tr>
            <tr>
                <td class="crono-date vermelho flush" data-dia="21 novembro à 16 janeiro 2015" data-descricao="Etapa Nacional 2014" colspan="2">
                    <table>
                        <tr>
                            <td class="this-or-this__this" data-dia="21 novembro à 16 janeiro 2015" data-descricao="Etapa Nacional 2014">14<br>dezembro<br>2014</td>
                            <td class="this-or-this__or" data-dia="21 novembro à 16 janeiro 2015" data-descricao="Etapa Nacional 2014">à</td>
                            <td class="this-or-this__this"  data-dia="21 novembro à 16 janeiro 2015" data-descricao="Etapa Nacional 2014">16<br>janeiro<br>2015</td>
                        </tr>
                    </table>
                </td>
                <td class="crono-date cinza-escuro" data-dia="06 março 2015" data-descricao="Reconhecimento Nacional 2014">06<br>março<br>2015</td>
            </tr>
        </table>
    </div>
</div>
</div>
