<div id="container" class="boxWhite container page-premiacao">
    <h2>PREMIAÇÃO</h2>
    <h3>Destaque valores positivos, que possam incentivar outras mulheres.</h3> 
    
    <p>O Prêmio SEBRAE Mulher de Negócios é composto por 2 (duas) etapas: estadual e nacional.</p>

    <h4>Etapa Estadual</h4>
    <p>Nesta etapa, podem ser reconhecidas como vencedoras estaduais até 3 (três) empreendedoras de cada estado e 3 (três) do Distrito Federal; uma para cada categoria prevista, podendo-se chegar a até 81 empreendedoras.</p>
    <p>
        <b>Todas Unidades da federação do SEBRAE, oferecerão as suas vencedoras:</b>
    </p>
    
    
    
    <ul>
        <li>Uma placa/ troféu de reconhecimento; </li>
        <li>Certificado de premiação;</li>
        <li>Direito ao uso do selo de vencedora, explicitando o ciclo;</li>
        <li>Um curso da Matriz de Soluções Educacionais e/ou 16 (dezesseis) horas técnicas de consultoria em gestão.</li>
    </ul>


    <h4>Etapa Nacional</h4>
    <p>Dentre os 81 relatos de empreendedoras, 3 (três) por Unidade da Federação ,
selecionados nessa etapa, serão avaliados e selecionados por uma comissão técnica
nacional, considerando os critérios de julgamento descritos no artigo 7º deste
regulamento, para a escolha de até 9 (nove) finalistas: 3 (três) representantes de
cada categoria <b>(Pequenos Negócios, Produtora Rural e Empreendedora Individual)</b>.</p>
    <p>
        As empreendedoras dos 9 (nove) relatos escolhidos serão as finalistas nacionais.

Todas as 81 receberão:
    </p>
    <ul>
        <li>Viagem para participar do evento da etapa nacional em
Brasília.</li>
    </ul>
    <p>As finalistas nacionais serão avaliadas e classificadas, considerando os critérios de
julgamento da seguinte forma:</p>
       <ul>
        <li>Três relatos, sem considerar a região, um de cada
categoria (Pequenos Negócios, Produtora Rural e Micro
Empreendedora Individual. ) receberão o troféu bronze; </li>
        <li>Três relatos, sem considerar a região, um de cada
categoria (Pequenos Negócios, Produtora Rural e Micro
Empreendedora Individual. receberão o troféu prata;</li>
        <li>Três relatos, sem considerar a região, um de cada
categoria (Pequenos Negócios, Produtora Rural e Micro
Empreendedora Individual.) receberão o troféu ouro.</li>
    </ul>
    <p>I – As ganhadoras do troféu ouro, prata e bronze receberão uma viagem para
capacitação em território nacional;</p>
    <p>II – Selo de vencedora nacional, explicitando o ciclo;</p>
    <p>III – As três ganhadoras nacionais receberão, além do troféu ouro, do selo e da
capacitação em território nacional, uma viagem internacional.</p>
    
        <ul>
        <li>As ganhadoras estaduais do prêmio só poderão concorrer
novamente após 2 (dois) anos da sua premiação.</li>
    </ul>
    
    <p>As ganhadoras nacionais do prêmio, contempladas com a viagem internacional, não
poderão concorrer mais ao Prêmio SEBRAE Mulher de Negócios.</p>
    
    <p>As candidatas receberão uma devolutiva com base em sua autoavaliação entregue
na inscrição.</p>
</div>
<?php /* ?>
<div class="navegacao">
    <a href="#" id="up"><i class="i ir bt-up">up</i></a>
    <a href="#" id="down"><i class="i ir bt-down">down</i></a>
</div>
<?php */ ?>