<div id="container" class="boxWhite container page-regulamento">
   <h2>REGULAMENTO</h1>
 <h3>2014</h3> 

 <p>
     <a href="<?php echo $this->baseUrl('/files/psmn2014-regulamento-2014.pdf'); ?>" title="Baixe aqui o regulamento">Baixe aqui o regulamento</a>
 </p>
 
<div id="page_1">

  <p class="p2 ft2">O Prêmio é uma parceria entre o Serviço Brasileiro de Apoio às Micro e Pequenas Empresas (SEBRAE), a Secretaria Especial de Políticas para as Mulheres (SPM), a Federação das Associações de Mulheres de Negócios e Profissionais do Brasil (BPW) e a Fundação Nacional da Qualidade (FNQ).</p>
  <p class="p3 ft1">Art. 1º - Objetivo</p>
  <p class="p4 ft1">Este regulamento estabelece normas, condições e diretrizes para selecionar e reconhecer as estórias de vida de mulheres de negócios, que transformaram seus sonhos em realidade e cujos relatos sirvam de exemplos e estímulo para outras mulheres desenvolverem seu comportamento empreendedor.</p>
  <p class="p5 ft1">Art. 2º - <nobr>Público-alvo</nobr></p>
  <p class="p6 ft1">O prêmio é dirigido a mulheres empreendedoras, com mais de 18 anos, que poderão concorrer em 3 (três) categorias:</p>
  <p class="p7 ft1">I &ndash; Pequenos Negócios: proprietárias de micro e pequenas empresas que estejam estabelecidas formalmente há, no mínimo, um ano. (data de abertura anterior a 01/03/2013, conforme consta no CNPJ);</p>
  <p class="p8 ft3">II &ndash; Produtora Rural: mulheres que explorem atividades agrícolas, pecuárias e/ou pesqueiras nas quais não sejam alteradas a composição e as características do produto in natura), e que estejam estabelecidas formalmente há, no mínimo, um ano. (data de abertura anterior a 01/03/2013, conforme documento de registro legal pertinente, descrito no artigo 7, parágrafo 2º);</p>
  <p class="p9 ft4">III &ndash; Micro Empreendedora Individual: mulheres que trabalhem por conta própria, tenham seu empreendimento legalizado, com faturamento máximo anual de até R$ 60.000,00 por ano, e não tenham participação em outra empresa como sócias ou titulares, e tenham até um(a) empregado(a) contratado(a) que receba o salário mínimo, ou o piso da categoria.</p>
  <p class="p10 ft1">(data de abertura anterior a 01/03/2013, conforme consta no CNPJ);</p>
  <p class="p11 ft7"><span class="ft5">§</span><span class="ft6">1º - o faturamento anual não poderá ultrapassar R$ 3.600.000,00 (três milhões e seiscentos mil reais) segundo o Estatuto Nacional das Microempresas e das Empresas de Pequeno Porte;</span></p>
  <p class="p12 ft1"><span class="ft5">§</span><span class="ft8">2º - não será permitida a participação de cooperativas, ONGs, OSCIPs, sindicatos, associações filantrópicas e outras de caráter semelhante, assim como empresas cujas proprietárias ou sócias sejam empregadas ou prestadoras de serviço das entidades promotoras do prêmio com acesso a informações privilegiadas do processo de avaliação.</span></p>
  <p class="p5 ft1">Art. 3º - Inscrições</p>
  <p class="p13 ft1">As inscrições terão início dia 08 de março de 2014, e se encerrarão às 23h59 do dia 31 de julho de 2014.</p>
  <p class="p14 ft1">Para fins de verificação do cumprimento do prazo de inscrição, será considerada a data de entrega no SEBRAE, a postagem no correio ou, ainda, o protocolo emitido pela Internet.</p>
  <p class="p15 ft1">As inscrições são gratuitas e poderão ser realizadas nas seguintes modalidades:</p>
  <p class="p16 ft1">I &ndash; inscrição eletrônica pela Internet no endereço: <span class="ft9">www.mulherdenegocios.sebrae.com.br</span></p>
  <p class="p17 ft1">II &ndash; inscrição em ficha que acompanha o regulamento, anexo I, também disponível em todas as unidades do SEBRAE.</p>
  <p class="p18 ft10">1</p>
</div>
<div id="page_2">
  <p class="p19 ft3"><span class="ft5">§</span><span class="ft11">1º - a candidatura só será considerada completa com o preenchimento de todos os campos da ficha de inscrição, acompanhada do relato escrito da empreendedora, da autoavaliação sobre o negócio (anexo III).</span></p>
  <p class="p4 ft1"><span class="ft5">§</span><span class="ft12">2º - a realização da inscrição implica na aceitação e concordância das condições deste regulamento.</span></p>
  <p class="p20 ft1"><span class="ft5">§</span><span class="ft13">3º - as participantes deverão observar os seguintes pontos no ato de inscrição:</span></p>
  <p class="p21 ft1">I &ndash; cada relato inscrito só poderá <nobr>referir-se</nobr> a um CNPJ e uma única vez no ciclo vigente;</p>
  <p class="p6 ft1">II &ndash; a candidata poderá <nobr>inscrever-se</nobr> pelo site (www.mulherdenegocios.sebrae.com.br) ou enviar pelo correio ou entregar a ficha de inscrição na unidade do SEBRAE onde estiver sediada a sua empresa, ou na sede do SEBRAE do seu Estado;</p>
  <p class="p22 ft1">III &ndash; o horário para recebimento da ficha de inscrição em todas as unidades do SEBRAE nas Unidades da Federação será o mesmo do funcionamento da entidade;</p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft14">4º - as inscrições incompletas, sem assinatura quando em papel, fora do padrão e do prazo deste regulamento serão desclassificadas.</span></p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft15">5º - as ganhadoras estaduais do prêmio só poderão concorrer novamente após 2 (dois) anos da sua premiação.</span></p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft14">6º - as ganhadoras nacionais do prêmio</span><span class="ft16">, </span>contempladas com a viagem internacional, não poderão concorrer mais ao Prêmio SEBRAE Mulher de Negócios.</p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft17">7º - as candidatas receberão uma devolutiva com base em sua autoavaliação entregue na inscrição.</span></p>
  <p class="p15 ft1">Art. 4° - Apresentação do Relato</p>
  <p class="p4 ft3">§ 1º - o relato poderá ser escrito a mão, considerando o formulário disponibilizado abaixo. O mínino será de 60 (sessenta) linhas e o máximo 120 (cento e vinte) linhas. Não serão aceitos anexos ou textos fora do formulário permitido. Se digitado, não deverá ter menos de 500 (quinhentas) palavras - 3000 caracteres, e não ultrapassar o máximo de 1200 (mil e duzentas) palavras &ndash; 7140 caracteres, incluindo o título. Caso contrário, o relato será devolvido à candidata para os devidos ajustes.</p>
  <p class="p15 ft1">§ 2º - o relato poderá ser digitado diretamente no site e deverá ter no mínimo 500 (quinhentas) palavras (3000 caracteres) a no máximo 1200 (mil e duzentas) palavras (7140 caracteres), incluindo o título.</p>
  <p class="p15 ft1">§ 3º - relatos fora dos padrões especificados nos § 1º e § 2º não serão aceitos.</p>
  <p class="p15 ft1">§ 4º - para escrever o relato, a empreendedora poderá seguir o roteiro do Anexo II.</p>
  <p class="p21 ft1">Art. 5º - Etapas</p>
  <p class="p3 ft1">O prêmio é composto por 2 (duas) etapas: estadual e nacional.</p>
  <p class="p4 ft1">Parágrafo único. As melhores pontuadas na etapa estadual receberão a visita de um verificador, que validará as informações apresentadas no relato.</p>
  <p class="p15 ft1">Etapa Estadual</p>
  <p class="p6 ft3">§ 1º - nesta etapa, os relatos inscritos serão avaliados e selecionados por uma comissão julgadora estadual, considerando os critérios de julgamento descritos no artigo 7º deste regulamento. Serão escolhidas até 3 (três) relatos de empreendedoras de cada Unidade da Federação: 1 (um) da categoria Pequenos Negócios, 1 (um) da categoria Produtora Rural e 1 (um) da categoria Micro Empreendedora Individual.</p>
  <p class="p7 ft1">I &ndash; o número total de relatos selecionados em todas as Unidades da Federação será, no máximo, de 81 (oitenta e um). Este número poderá ser menor caso as histórias não atendam aos critérios estabelecidos neste regulamento.</p>
  <p class="p24 ft10">2</p>
</div>
<div id="page_3">
  <p class="p25 ft1"><span class="ft1">II</span><span class="ft18">&ndash; cada SEBRAE da Unidade da Federação oferecerá às suas vencedoras:</span></p>
  <p class="p26 ft1"><span class="ft5">a)</span><span class="ft13">uma placa/ troféu de reconhecimento;</span></p>
  <p class="p27 ft1"><span class="ft19">b)</span><span class="ft13">certificado de premiação;</span></p>
  <p class="p26 ft1"><span class="ft5">c)</span><span class="ft13">direito ao selo de vencedora, explicitando o ciclo;</span></p>
  <p class="p28 ft1"><span class="ft19">d)</span><span class="ft13">um curso da Matriz de Soluções Educacionais e/ou 16 (dezesseis) horas técnicas de consultoria em gestão.</span></p>
  <p class="p15 ft1">Etapa Nacional</p>
  <p class="p4 ft3">§ 2º - os 81 (oitenta e um) relatos de empreendedoras, 3 (três) por Unidade da Federação , selecionados nessa etapa, serão avaliados e selecionados por uma comissão técnica nacional, considerando os critérios de julgamento descritos no artigo 7º deste regulamento, para a escolha de até 9 (nove) finalistas: 3 (três) representantes de cada categoria (Pequenos Negócios, Produtora Rural e Empreendedora Individual ).</p>
  <p class="p29 ft1">I &ndash; as empreendedoras dos 9 (nove) relatos escolhidos serão as finalistas nacionais;</p>
  <p class="p30 ft1">II &ndash; todas as 81 receberão;</p>
  <p class="p26 ft1"><span class="ft5">a)</span><span class="ft13">viagem para participar do evento da etapa nacional em Brasília.</span></p>
  <p class="p31 ft1">II &ndash; os casos excepcionais quanto ao número de finalistas serão deliberados pela Comissão Julgadora Nacional, que é soberana em suas decisões.</p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft14">3º - as finalistas nacionais serão avaliadas e classificadas, considerando os critérios de julgamento descritos no artigo 7º deste regulamento, da seguinte forma:</span></p>
  <p class="p32 ft7"><span class="ft5">a)</span><span class="ft6">3 (três) relatos, sem considerar a região, 1 (um) de cada categoria (Pequenos Negócios, Produtora Rural e Micro Empreendedora Individual. ) receberão o troféu bronze;</span></p>
  <p class="p32 ft1"><span class="ft19">b)</span><span class="ft14">3 (três) relatos, sem considerar a região, 1 (um) de cada categoria (Pequenos Negócios, Produtora Rural e Micro Empreendedora Individual. receberão o troféu prata;</span></p>
  <p class="p32 ft1"><span class="ft5">c)</span><span class="ft15">3 (três) relatos, sem considerar a região, 1 (um) de cada categoria (Pequenos Negócios, Produtora Rural e Micro Empreendedora Individual.) receberão o troféu ouro.</span></p>
  <p class="p14 ft1">I &ndash; as ganhadoras do troféu ouro, prata e bronze receberão uma viagem para capacitação em território nacional;</p>
  <p class="p7 ft1"><span class="ft5">a)</span><span class="ft8">a capacitação será em evento de mercado, no segmento de empreendedorismo e/ou gestão empresarial, em data e local a serem informados posteriormente.</span></p>
  <p class="p33 ft1"><span class="ft19">b)</span><span class="ft13">selo de vencedora nacional, explicitando o ciclo;</span></p>
  <p class="p6 ft1"><span class="ft1">II</span><span class="ft14">&ndash; as 3 (três) ganhadoras nacionais receberão, além do troféu ouro, do selo e da capacitação em território nacional, uma viagem internacional.</span></p>
  <p class="p7 ft1"><span class="ft5">a)</span><span class="ft14">a agenda da viagem estará relacionada ao tema gestão empresarial e/ou ao segmento de negócio das vencedoras. O destino será definido pela coordenação do Prêmio SEBRAE Mulher de Negócios.</span></p>
  <p class="p22 ft1"><span class="ft5">§</span><span class="ft20">4º - os cursos e as viagens, patrocinados pelos promotores do Prêmio, são individuais e intransferíveis.</span></p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft21">5º - as providências relativas à documentação para a viagem internacional serão de responsabilidade de cada participante.</span></p>
  <p class="p15 ft1">Art. 6º - Comissões Julgadoras</p>
  <p class="p3 ft1">As comissões serão constituídas da seguinte forma:</p>
  <p class="p34 ft10">3</p>
</div>
<div id="page_4">
  <p class="p35 ft1">I &ndash; as comissões julgadoras da etapa estadual poderão ser constituídas por representantes do SEBRAE local e entidades parceiras, totalizando no mínimo 3 (três) integrantes;</p>
  <p class="p36 ft1">II &ndash; a comissão julgadora da etapa nacional será composta por 2 (dois) representantes do SEBRAE Nacional e 1 (um) de cada entidade parceira, totalizando 5 (cinco) membros.</p>
  <p class="p37 ft1"><span class="ft5">§</span><span class="ft20">1º - não poderão integraras comissões profissionais vinculados direta ou indiretamente a qualquer candidata.</span></p>
  <p class="p37 ft1"><span class="ft5">§</span><span class="ft14">2º - integrantes do processo de avaliação, de todas as etapas, cumprirão as exigências do Código de Ética deste Prêmio assumindo o compromisso de sigilo em relação aos dados e às informações que chegarem a seu conhecimento.</span></p>
  <p class="p38 ft1"><span class="ft5">§</span><span class="ft15">3º - em caso de empate, o presidente da Comissão Julgadora terá, além do seu voto, o voto de decisão.</span></p>
  <p class="p39 ft1">Art. 7° - Critérios de Julgamento</p>
  <p class="p40 ft1">No julgamento dos relatos serão avaliados os seguintes aspectos:</p>
  <p class="p41 ft1"><span class="ft19">1.</span><span class="ft12">Superação da mulher;</span></p>
  <p class="p42 ft1"><span class="ft19">2.</span><span class="ft21">Visão de Futuro;</span></p>
  <p class="p41 ft1"><span class="ft19">3.</span><span class="ft21">Ideias inovadoras e adaptação às novas tendências;</span></p>
  <p class="p42 ft1"><span class="ft19">4.</span><span class="ft21">Atuação democrática, transparente, inspiradora e motivadora;</span></p>
  <p class="p41 ft1"><span class="ft19">5.</span><span class="ft12">Participação ativa nos negócios, perseverança e superação dos desafios;</span></p>
  <p class="p42 ft1"><span class="ft19">6.</span><span class="ft21">Ambiente participativo e agradável para quem trabalha no seu negócio;</span></p>
  <p class="p41 ft1"><span class="ft19">7.</span><span class="ft21">Estabelecimento de relacionamentos duradouros com os clientes;</span></p>
  <p class="p42 ft1"><span class="ft19">8.</span><span class="ft21">Preocupação com a preservação do meio ambiente e da cultura da sua região;</span></p>
  <p class="p41 ft1"><span class="ft19">9.</span><span class="ft12">Estabelecimento de parcerias para o desenvolvimento das atividades;</span></p>
  <p class="p43 ft1"><span class="ft19">10.</span><span class="ft18">Lições aprendidas (por meio de experimentações, erros cometidos ou compartilhamento de informações);</span></p>
  <p class="p44 ft1"><span class="ft19">11.</span><span class="ft13">Crescimento dos resultados obtidos;</span></p>
  <p class="p41 ft1"><span class="ft19">12.</span><span class="ft13">Contribuição para o desenvolvimento de outras empreendedoras.</span></p>
  <p class="p45 ft1"><span class="ft5">§</span><span class="ft22">1º - as informações apresentadas pelas candidatas serão examinadas pela equipe técnica do SEBRAE local que visitará as empresas com os relatos melhor avaliados, de acordo com o número de empreendimentos aptos para verificação.</span></p>
  <p class="p38 ft1"><span class="ft5">§</span><span class="ft15">2º - os empreendimentos cujos relatos forem os melhores na avaliação deverão apresentar, na ocasião da visita, os documentos que comprovem a regularidade fiscal e estatutária, bem como enviar para o SEBRAE local 1(uma) cópia dos mesmos:</span></p>
  <table class="" cellpadding="0" cellspacing="0"  border="1">
    <tbody>
    <tr>
      <td><p class=" ">Documentação</p></td>
      <td style="width: 80px;"><p class="">Pequenos Negócios</p></td>
      <td style="width: 80px;"><p class="">Produtora Rural</p></td>
      <td style="width: 80px; padding: 0px;"><p class="">Micro Empreendedora Individual</p></td>
    </tr>
    <tr>
      <td class="tr3 td8"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td9"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td10"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td11"><p class="p48 ft24">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr4 td4">Cadastro Nacional de Pessoa Jurídica (CNPJ)</td>
      <td class="tr4 td5"><p class="p49 ft25">X</p></td>
      <td class="tr4 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr4 td7"><p class="p50 ft1">X (CCMEI)</p></td>
    </tr>
    <tr>
      <td class="tr5 td8"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td9"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td10"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td11"><p class="p48 ft26">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4">Certidão Negativa de Débito junto à Previdência Social</td>
      <td class="tr0 td5"><p class="p49 ft25">X</p></td>
      <td class="tr0 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td7"><p class="p50 ft1">X</p></td>
    </tr>
    <tr>
      <td class="tr1 td4"><p class="p46 ft1">INSS</p></td>
      <td class="tr1 td5"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr1 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr1 td7"><p class="p48 ft23">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr5 td8"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td9"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td10"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td11"><p class="p48 ft26">&nbsp;</p></td>
    </tr>
    
    <?php /* ?>
    
    </tbody>
  </table>
</div>
 
<div id="page_5">
  <div class="dclr"></div>
  <table class="t1" cellpadding="0" cellspacing="0"  border="1">
    <tbody>
        <?php */ ?>
        
    <tr>
      <td class="tr0 td0"><p class="p46 ft27">Regularidade do Empregador - Certidão Negativa do FGTS &ndash; Fundo de Garantia por Tempo de Serviço</p></td>
      <td class="tr0 td1" style="width: 80px;"><p class="p52 ft1">X</p></td>
      <td class="tr0 td2" style="width: 80px;"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td3" style="width: 90px; padding: 0px;"><p class="p50 ft1">X</p></td>
    </tr>
    <tr>
      <td class="tr6 td4"><p class="p46 ft27"></p></td>
      <td class="tr6 td5"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr6 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr6 td7"><p class="p48 ft23">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p class="p46 ft1">Certidão Negativa de Débito Estadual junto à Secretaria da Fazenda do Estado</p></td>
      <td class="tr4 td5"><p class="p52 ft1">X</p></td>
      <td class="tr4 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr4 td7"><p class="p49 ft25">X</p></td>
    </tr>
    <tr>
      <td class="tr5 td8"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td9"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td10"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td11"><p class="p48 ft26">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p class="p46 ft1">Certidão Conjunta de Débitos relativos a Tributos Federais e à Dívida Ativa da União</p></td>
      <td class="tr4 td5"><p class="p52 ft1">X</p></td>
      <td class="tr4 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr4 td7"><p class="p49 ft25">X</p></td>
    </tr>
    <tr>
      <td class="tr5 td8"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td9"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td10"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td11"><p class="p48 ft26">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p class="p46 ft1">Recibo de entrega da Declaração da RAIS &ndash; Relação Anual de Informações Sociais (último exercício)</p></td>
      <td class="tr0 td5"><p class="p52 ft1">X</p></td>
      <td class="tr0 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td7"><p class="p53 ft19">X(se tiver empregado)</p></td>
    </tr>
    <tr>
      <td class="tr3 td8"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td9"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td10"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td11"><p class="p48 ft24">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p class="p46 ft29">Contrato social com última alteração contratual ou Estatuto</p></td>
      <td class="tr4 td5"><p class="p52 ft1">X</p></td>
      <td class="tr4 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr4 td7"><p class="p48 ft23">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr3 td8"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td9"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td10"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td11"><p class="p48 ft24">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p class="p46 ft29">Declaração da condição de Micro Empreendedor Individual (CCMEI)</p></td>
      <td class="tr0 td5"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td7"><p class="p49 ft25">X</p></td>
    </tr>
    <tr>
      <td class="tr7 td8"><p class="p48 ft28">&nbsp;</p></td>
      <td class="tr7 td9"><p class="p48 ft28">&nbsp;</p></td>
      <td class="tr7 td10"><p class="p48 ft28">&nbsp;</p></td>
      <td class="tr7 td11"><p class="p48 ft28">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p class="p46 ft19">Declaração das responsáveis pela empresa, assinada também pelo contador, relatando que a mesma não ultrapassa o limite máximo de enquadramento de micro e pequena empresa, conforme Estatuto Nacional das Microempresas e das Empresas de Pequeno Porte <nobr>&ndash;&ndash;</nobr> Base 2013</p></td>
      <td class="tr0 td5"><p class="p48 ft23">X</p></td>
      <td class="tr0 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td7"><p class="p48 ft23">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr5 td8"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td9"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td10"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td11"><p class="p48 ft26">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p class="p46 ft1">Cópia da Identidade e CPF</p></td>
      <td class="tr0 td5"><p class="p52 ft1">X</p></td>
      <td class="tr0 td6"><p class="p54 ft1">X</p></td>
      <td class="tr0 td7"><p class="p49 ft25">X</p></td>
    </tr>
    <tr>
      <td class="tr5 td8"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td9"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td10"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td11"><p class="p48 ft26">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p class="p46 ft1">Inscrição Estadual de Produtor ou Declaração de Aptidão ao PRONAF (DAP) ou CNPJ ou Registro no Ministério da Pesca Declaração Anual para o MEI &ndash; <nobr>DASN-Simei</nobr> (último exercício)</p></td>
      <td class="tr4 td5"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr4 td6"><p class="p54 ft1">X</p></td>
      <td class="tr4 td7"><p class="p48 ft23">X</p></td>
    </tr>
    <tr>
      <td class="tr5 td8"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td9"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td10"><p class="p48 ft26">&nbsp;</p></td>
      <td class="tr5 td11"><p class="p48 ft26">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr0 td4"><p class="p46 ft19">Declaração da empreendedora, relatando que a mesma não ultrapassa o limite máximo de enquadramento de Micro Empreendedora Individual, conforme Lei Complementar 128 <nobr>&ndash;&ndash;</nobr> 19/12/2008.</p></td>
      <td class="tr0 td5"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td6"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr0 td7"><p class="p48 ft23">X</p></td>
    </tr>
    <tr>
      <td class="tr3 td8"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td9"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td10"><p class="p48 ft24">&nbsp;</p></td>
      <td class="tr3 td11"><p class="p48 ft24">&nbsp;</p></td>
    </tr>
    <tr>
      <td class="tr4 td4"><p class="p46 ft19">Declaração da produtora rural, de próprio punho, relatando que a mesma não ultrapassou o limite máximo de faturamento anual de R$ 3.600.000,00 <nobr>&ndash;&ndash;</nobr> base 2013.</p></td>
      <td class="tr4 td5"><p class="p48 ft23">&nbsp;</p></td>
      <td class="tr4 td6"><p class="p48 ft23">X</p></td>
      <td class="tr4 td7"><p class="p48 ft23">&nbsp;</p></td>
    </tr>
    </tbody>
  </table>
  <p class="p55 ft1">§ 3º - Se os fatos relatados não puderem ser comprovados ou se for constatado pela equipe técnica não serem verdadeiros, a candidata será desclassificada.</p>
</div>
<div id="page_6">
  <p class="p57 ft1">Art. 8° - Disposições Gerais</p>
  <p class="p4 ft1">O objetivo dos parceiros ao instituir o Prêmio SEBRAE Mulher de Negócios é o de evidenciar o espírito empreendedor da mulher e de utilizar, em seus cursos e palestras, os melhores relatos como ferramenta educacional e de incentivo.</p>
  <p class="p12 ft1">§ 1º - as vencedoras se comprometem a participar de eventos promovidos pelo SEBRAE ou instituições parceiras para relatar suas experiências;</p>
  <p class="p58 ft1">I &ndash; o SEBRAE ou a instituição parceira agendará com antecedência os eventos com a empreendedora, arcando com as despesas de deslocamento e hospedagem.</p>
  <p class="p59 ft37"><span class="ft5">§</span><span class="ft36">2º - as candidatas e as vencedoras de qualquer etapa cedem por tempo indeterminado sem ônus para os realizadores e promotores do Prêmio o direito de uso e a divulgação de seus relatos, imagens, sons e qualquer material complementar ou ilustrativo entregues para concorrer a este Prêmio, ou dele oriundos, em eventos; palestras; feiras; seminários; cursos presenciais; cursos virtuais; tradução para outros idiomas; assim como veiculação em todas as mídias disponíveis utilizadas pelo Sistema SEBRAE e instituições parceiras; para distribuição em bibliotecas, escolas, organizações não governamentais e quaisquer instituições que queiram fazer uso educacional, ou para promover ou disseminar o empreendedorismo, sem quaisquer restrições ou pagamentos.</span></p>
  <p class="p60 ft1"><span class="ft5">§</span><span class="ft13">3º - os materiais produzidos em decorrência do prêmio serão de propriedade do SEBRAE.</span></p>
  <p class="p61 ft1"><span class="ft5">§</span><span class="ft15">4º - as vencedoras terão direito aos prêmios oferecidos pelo SEBRAE estadual além dos prêmios indicados neste regulamento.</span></p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft14">5º - qualquer outra liberalidade do SEBRAE em relação a uma vencedora ou grupo de vencedoras não constituirá em direito de reivindicação das demais.</span></p>
  <p class="p23 ft1"><span class="ft5">§</span><span class="ft8">6º - os casos considerados omissos serão submetidos à coordenação nacional do Prêmio, cuja decisão será soberana, não cabendo recurso ou apelação.</span></p>
  <p class="p62 ft1">Brasília, 2014</p>
  <!--p class="p63 ft10">6</p-->
</div>
<div id="page_7">
<p class="p57 ft38">Anexo I</p>
<p class="p3 ft1">Ficha de Inscrição</p>
<p class="p64 ft1">(Esta ficha só será válida se o texto do relato da candidata e o questionário de autoavaliação estiverem em conformidade e anexos a ela.)</p>
<p class="p15 ft1">* Campos obrigatórios</p>
<p class="p3 ft1">PREENCHIMENTO PELA CANDIDATA</p>
<p class="p21 ft1">Dados da empresa</p>
<p class="p3 ft1">Categoria do Prêmio*:</p>
<p class="p21 ft1">( ) Pequenos Negócios ( ) Produtora Rural ( ) Microempreendedora Individual</p>
<p class="p21 ft1">Razão Social*:__________________________________________________________</p>
<p class="p3 ft1">Nome Fantasia*:_________________________________________________________</p>
<p class="p21 ft1">CNPJ*:________________________________________________________________</p>
<p class="p3 ft1">Data da abertura da empresa*:___/____/___ Número de empregados*______________</p>
<p class="p21 ft1">Endereço* (Rua, Av.):____________________________________________________</p>
<p class="p3 ft1">Número*: ___________________________Complemento: _______________________</p>
<p class="p21 ft1">Bairro:________________</p>
<p class="p3 ft1">Estado*:______ Cidade*:__________________</p>
<p class="p21 ft1">CEP*:____________</p>
<p class="p3 ft1">Telefone*: ( ) ____________________</p>
<p class="p21 ft1">Site: ________________________ <nobr>e-mail:________________________</nobr></p> 
<br />
<p class="p3 ft1">Faturamento anual em 2013 (R$)*:</p><br />
<p class="p21 ft1">( ) 0,01 a 60.000,00 &ndash; Microempreendedor Individual</p><br />
<p class="p21 ft1">( ) 0,01 a 360.000,00</p><br />
<p class="p21 ft1">( ) 360.001,00 a 3.600.000,00</p><br />
<br />
<p class="p21 ft1">Categoria setorial*:</p><br />
<p class="p21 ft1">( ) Agronegócio</p><br />
<p class="p21 ft1">( ) Comércio</p><br />
<p class="p21 ft1">( ) Indústria</p><br />
<p class="p21 ft1">( ) Serviços</p><br />
<p class="p21 ft1">( ) Artesanato</p><br />

<p class="p21 ft1"></p>


<p class="p15 ft1">Atividade Econômica (Código CNAE e atividade)*: _____________________________</p>
<p class="p67 ft19">Descreva, de forma resumida, quais os principais produtos e/ou serviços de sua empresa e seus principais clientes*:_______________________________________________________________</p>
<p class="p68 ft1">______________________________________________________________________________</p>
<p class="p3 ft1">______________________________________________________________________________</p> <br />
<p class="p21 ft1">Dados da candidata</p><br />
<p class="p3 ft1">Nome completo*:________________________________________________________</p>
<p class="p21 ft1">Nome para tratamento:___________________________________________________</p>
<p class="p3 ft1">CPF*:______________________________ Cargo* ( ) Proprietária/Sócia ( ) Representante</p>
</div>
<div id="page_8">


  <p class="p70 ft1">Endereço* (Rua, Av.):____________________________________________________</p>
  <p class="p71 ft1">Número*: ___________________________Complemento: _______________________</p>
  <p class="p72 ft1">Bairro:________________ Estado*:______ Cidade*:__________________</p>
  <p class="p71 ft1">CEP*:____________</p>
  <p class="p72 ft1">Telefone fixo*: ( ) __________________ Telefone celular: ( ) ________________</p>
  
<p class="p48 ft19"><nobr>E-mail:________________________</nobr></p>
<p class="p48 ft1">Data de nascimento: ___/____/___</p>
<p class="p48 ft1">Nível de escolaridade*:</p> <br />
<p class="p48 ft1">( ) Sem escolaridade</p>
<p class="p48 ft1">( ) Ensino Fundamental completo</p>
<p class="p48 ft1">( ) Ensino Fundamental incompleto</p>
<p class="p48 ft1">( ) Ensino Médio completo</p>
<p class="p48 ft1">( ) Ensino Médio incompleto</p>
<p class="p48 ft1">( ) Superior completo</p>
<p class="p48 ft1">( ) Superior incompleto</p>
<p class="p48 ft1">( ) Especialização</p>
<p class="p48 ft1">( ) Mestrado</p>
<p class="p48 ft1">( ) Doutorado</p>
<p class="p48 ft1"></p>

<p class="p48 ft1"></p>

<p class="p48 ft1"></p>
<p class="p48 ft1"></p>
<p class="p48 ft1"></p>
<p class="p48 ft1"></p>
<p class="p48 ft1"></p>
<p class="p48 ft1"></p>
<p class="p48 ft1"></p>
<br />
Faixa etária*: <br />
( ) Menos de 25 anos<br />
( ) Entre 25 e 29 anos<br />
( ) Entre 30 e 34 anos<br />
( ) Entre 35 e 39 anos<br />
( ) Entre 40 e 44 anos<br />
( ) Entre 45 e 49 anos<br />
( ) Acima de 50 anos<br />
<br />
Como você tomou conhecimento do Prêmio SEBRAE Mulher de Negócios?<br />
Promotores do Prêmio. Qual? <br />
( ) SEBRAE
( ) BPW 
( ) SPM 
( ) FNQ
( ) Revista 
( ) Recebi uma ligação 
( ) Jornal
( ) Rádio
( ) TV
( ) Internet
( ) Rede Social
( ) Placa/faixa/outdoor/busdoor ou similar
( ) Conhecidos/amigos ou familiares
( ) Parceiros Locais
( ) Outro meio
<br />
já participou de algum destes programas do SEBRAE? <br />
Empretec ( ) Negócio a Negócio ( ) SEBRAE Mais ( ) SEI ( ) ALI ( ) SEBRAEtec ( ) Na Medida <br />
( ) Aceito participar do Prêmio SEBRAE Mulher de Negócios, conforme regulamento do Prêmio, ciclo 2014.
  <p class="p83 ft1"></p>
  <p class="p71 ft1">Data: ___/____/___</p><br />
  <p class="p72 ft1">Assinatura da participante: ________________________________________________</p>
</div>
<div id="page_9">
  <p class="p57 ft38">Anexo II</p>
  <p class="p3 ft1">ROTEIRO PARA ESCREVER O SEU RELATO</p>
  <p class="p21 ft1">Para contar o seu relato como Mulher de Negócios, você poderá considerar os seguintes pontos.</p>
  <p class="p21 ft1">Consulte também o Guia de Redação disponível no site www.mulherdenegocios.sebrae.com.br.</p>
  <p class="p3 ft1">Título do relato (1 linha)</p>
  <p class="p64 ft1">O título é uma forma de resumir o que o relato tem de mais importante. Sugestão: escreva o título depois do relato pronto.</p>
  <p class="p20 ft1"><span class="ft19">1.</span><span class="ft21">Criação do Negócio: Conte como tudo começou</span></p>
  <p class="p85 ft1">Quais informações foram utilizadas para a concretização do sonho? O que ou quem a inspirou a montar o seu negócio?</p>
  <p class="p86 ft19">Que novidade ou novas tendências buscava trazer ao iniciar seu negócio? O que seu produto ou serviço tinha de diferente dos outros?</p>
  <p class="p87 ft1">Como o fato de ser mulher influenciou sua decisão de abrir o negócio?</p>
  <p class="p88 ft1">Você acha que teve dificuldades específicas por ser mulher? Se sim, que ações criativas buscou para solucionar as dificuldades?</p>
  <p class="p20 ft1"><span class="ft19">2.</span><span class="ft21">Desenvolvimento (Condução) do Negócio: Conte com as coisas acontecem no </span><nobr>dia-a-dia</nobr></p>
  <p class="p89 ft1">Quais valores pessoais (aquilo que acredita) busca passar com a condução de seu negócio? Como compartilha as informações? Consulta e/ou envolve os colaboradores nas tomadas de decisão?</p>
  <p class="p90 ft1">Como está estruturado o seu negócio (regras de funcionamento, pessoas envolvidas, e o local de suas atividades)?</p>
  <p class="p91 ft1">Dê exemplos do bom uso dos recursos que dispõe.</p>
  <p class="p92 ft1">Como você participa da condução das atividades do seu negócio, incluindo relacionamento com clientes, colaboradores, fornecedores, comunidade, parceiros?</p>
  <p class="p93 ft1">Como você reage diante dos desafios ou obstáculos na condução do seu negócio? Como são selecionados seus colaboradores? Há uma preocupação com a redução de desigualdades sociais?</p>
  <p class="p94 ft1">Que benefícios são oferecidos aos seus colaboradores (empregados) para que eles se sintam mais motivados?</p>
  <p class="p95 ft39">Como as opiniões dos colaboradores são consideradas na gestão do seu negócio? O que você faz para tornar o ambiente de trabalho agradável? Cite exemplos.</p>
  <p class="p96 ft37">Como você e seus funcionários fazem para conhecer as necessidades dos seus clientes? Como você se relaciona com seus clientes? Esse relacionamento é duradouro? Cite exemplos. Quando seus clientes reclamam de algum produto ou de demora na entrega ou mesmo do atendimento, como vocês respondem a eles? Cite exemplos das soluções dadas?</p>
  <p class="p97 ft1">Como você avalia a satisfação dos seus clientes?</p>
  <p class="p98 ft1">Como você mantém os seus produtos/serviços atualizados? Você observa as tendências e tecnologias de mercado?</p>
  <p class="p91 ft1">Que ações são adotadas por sua empresa para preservar o meio ambiente?</p>
  <p class="p99 ft1">Quais benefícios você acredita que seu negócio trouxe para sua comunidade / bairro / município? (benefícios ao meio ambiente, outras mulheres, desenvolvimento econômico, benefícios sociais, facilidade de acesso a serviços diferenciados, etc.)</p>
  <p class="p100 ft1">Como obtém os recursos necessários para incrementar o seu negócio?</p>
  <p class="p101 ft1"><span class="ft19">3.</span><span class="ft13">Resultados: Realizações e Contribuições</span></p>
  <p class="p102 ft19">Que soluções adotou como resultado do amadurecimento do negócio, problemas enfrentados, ou dos relacionamentos mantidos? Se você pudesse voltar no tempo, faria algo</p>
</div>
<div id="page_10">
  <p class="p104 ft1">diferente? Cite exemplos de melhorias realizadas que partiram de lições aprendidas dos erros cometidos em seu negócio.</p>
  <p class="p58 ft1">Como você percebe que seu negócio está melhorando (aumento de faturamento, de clientes, melhoria da qualidade dos produtos/serviços, satisfação dos colaboradores)?</p>
  <p class="p29 ft1">O que pensa para o futuro do seu negócio?</p>
  <p class="p16 ft1">Quais são os próximos passos para assegurar o futuro do seu negócio (planos e metas)?</p>
  <p class="p30 ft1">Como o seu negócio serve de exemplo para a formação de novas empreendedoras?</p>
  <p class="p16 ft1">Em sua opinião, o que é preciso fazer para ter sucesso como empreendedora?</p>
  <p class="p30 ft1">Que mensagem você gostaria de passar para as mulheres que estão iniciando um negócio?</p>
  <p class="p105 ft1">ORIENTAÇÕES PARA UMA BOA NARRATIVA:</p>
  <p class="p4 ft1">A narrativa deve atrair a atenção de quem vai ler. Por isso, deve passar emoção. O que você vai contar deve ser real e verdadeiro, pois se passar para a fase de visitas as informações terão que ser evidenciadas.</p>
  <p class="p22 ft3">É desejável destacar valores positivos, que possam incentivar outras pessoas, como iniciativa, visão de futuro, pensamento sistêmico, aprendizado, inovação, valorização das pessoas e do gênero feminino, planejamento, estabelecimento de metas, busca de informações e de oportunidades. Caso algumas dessas características estejam presentes no seu caminho de empreendedora, <nobr>destaque-as</nobr> em sua narrativa.</p>
</div>
<div id="page_11">
  <p class="p107 ft38">Anexo III</p>
  <p class="p108 ft0">AUTOAVALIAÇÃO SOBRE O NEGÓCIO</p>
  <table class="t4" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
    <td class="tr6 td40"></td>
    <td class="tr6 td41"><p class="p109 ft40">ASSINALE O GRAU DE CONCORDÂNCIA</p></td>
    <td class="tr6 td42"><p class="p110 ft41">DISCORDO</p></td>
    <td class="tr6 td43"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td44"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td44"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td45"><p class="p111 ft41">CONCORDO</p></td>
  </tr>
  <tr>
    <td class="tr9 td40"></td>
    <td class="tr9 td41"><p class="p109 ft40">COM CADA UMA DAS AFIRMAÇÕES</p></td>
    <td rowspan="2" class="tr2 td42"><p class="p112 ft41">TOTALMENTE</p></td>
    <td class="tr9 td43"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td44"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td44"><p class="p48 ft23">&nbsp;</p></td>
    <td rowspan="2" class="tr2 td45"><p class="p111 ft41">TOTALMENTE</p></td>
  </tr>
  <tr>
    <td class="tr19 td40"></td>
    <td rowspan="2" class="tr8 td41"><p class="p113 ft40">ABAIXO</p></td>
    <td class="tr19 td43"><p class="p48 ft42">&nbsp;</p></td>
    <td class="tr19 td44"><p class="p48 ft42">&nbsp;</p></td>
    <td class="tr19 td44"><p class="p48 ft42">&nbsp;</p></td>
  </tr>
  <tr>
    <td class="tr10 td40"></td>
    <td rowspan="2" class="tr20 td42"><p class="p110 ft41">0</p></td>
    <td rowspan="2" class="tr20 td43"><p class="p82 ft41">1</p></td>
    <td rowspan="2" class="tr20 td44"><p class="p82 ft41">2</p></td>
    <td rowspan="2" class="tr20 td44"><p class="p82 ft41">3</p></td>
    <td rowspan="2" class="tr20 td45"><p class="p114 ft41">4</p></td>
  </tr>
  <tr>
    <td class="tr5 td40"></td>
    <td class="tr5 td41"><p class="p48 ft26">&nbsp;</p></td>
  </tr>
  </tbody>
  </table>
  
  <p class="p115 ft5"><span class="ft5">1)</span><span class="ft43">Antes de abrir o negócio, procurei informações no mercado, pesquisei o que já existia e avaliei bem tudo o que precisaria fazer antes de tomar a decisão.</span></p>
  <p class="p116 ft29">Informar quais informações e pesquisas foram feitas antes de você abrir o negócio:</p>
  <p class="p117 ft5"><span class="ft5">2)</span><span class="ft43">Na criação do negócio, trouxe idéias inovadoras para o mercado e demonstrei que meu produto/serviço tinha um diferencial sobre os outros.</span></p>
  <p class="p116 ft29">Descreva o diferencial que seu produto ou serviço tem sobre o dos concorrentes:</p>
  <p class="p118 ft5"><span class="ft5">3)</span><nobr><span class="ft43">Relaciono-me</span></nobr> pessoalmente com meus clientes, colaboradores, comunidade e fornecedores, e posso demonstrar o caráter duradouro desses relacionamentos.</p>
  <p class="p119 ft29">Dê exemplos que demonstrem que o relacionamento com seus clientes, colaboradores, comunidade e fornecedores é duradouro:</p>
  <p class="p120 ft10"><span class="ft5">4)</span><span class="ft44">Tenho uma atuação democrática e transparente para tomar decisões e atuo de forma inspiradora e motivadora para mobilizar as pessoas que preciso na condução das atividades do negócio?</span></p>
  <p class="p121 ft29">Dê um exemplo que demonstre que sua forma de atuação na condução do negócio é inspiradora e motivadora:</p>
  <p class="p122 ft46"><span class="ft5">5)</span><span class="ft45">Remunero, reconheço e dou incentivos aos meus colaboradores, de forma que esses se sintam estimulados à busca de melhores resultados para</span></p>
</div>
<div id="page_12">

  <div class="dclr"></div>
  <p class="p124 ft5">o negócio.</p>
  <p class="p125 ft29">Citar formas utilizadas para incentivar e reconhecer os colaboradores:</p>
  <p class="p126 ft19">6) Conheço as necessidades dos meus clientes.</p>
  <p class="p127 ft29">Descrever os meios de que se utiliza para identificar as necessidades e expectativas de seus clientes.</p>
  <p class="p128 ft48"><span class="ft5">7)</span><span class="ft47">Tenho uma preocupação com o meio ambiente no desenvolvimento das atividades da empresa.</span></p>
  <p class="p129 ft29">Informar que ações são adotadas na empresa para a preservação do meio ambiente.</p>
  <p class="p130 ft10"><span class="ft5">8)</span><span class="ft44">Planejo o futuro que desejo para o meu negócio e defino estratégias e planos para </span><nobr>concretizá-lo.</nobr></p>
  <p class="p131 ft29">Descrever a visão de futuro para o negócio</p>
  <p class="p132 ft50"><span class="ft5">9)</span><span class="ft49">Tenho exemplos de melhorias que foram realizadas a partir de lições aprendidas dos erros cometidos na gestão do negócio.</span></p>
  <p class="p129 ft29">Citar um exemplo de uma melhoria implementada recentemente.</p>
  <p class="p133 ft19"><span class="ft5">10)</span><span class="ft51">Tenho medidas para avaliar os resultados gerados pelo negócio?</span></p>
  <p class="p134 ft29">Apresentar quais informações são utilizadas para se avaliar o desempenho do negócio.</p>
</div>
<div id="page_13">


<div class="dclr"></div>
</div>
<div id="page_14">



<p class="p137 ft38">Anexo IV</p>
<p class="p138 ft0">CARACTERÍSTICAS DE COMPORTAMENTO EMPREENDEDOR</p>
<p class="p139 ft1">Você irá preencher as questões de 1 a 30, correspondentes às Características de Comportamento Empreendedor.</p>
<p class="p140 ft1">Leia cuidadosamente cada afirmação e decida qual a resposta que melhor se aplica à sua realidade. Marque o número selecionado na linha à direita de cada afirmação.</p>
<p class="p141 ft1">1 = dificilmente acontece 2 = às vezes acontece 3 = sempre acontece Exemplo:</p>
<table class="t5" cellpadding="0" cellspacing="0">
<tbody><tr>
    <td class="tr6 td46"><p class="p46 ft1"><nobr>Mantenho-me</nobr> calma em situações tensas</p></td>
    <td class="tr6 td47"><p class="p142 ft1">1</p></td>
    <td class="tr6 td47"><p class="p142 ft1">2</p></td>
    <td class="tr6 td48"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr21 td49"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr21 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr21 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr21 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
</tbody></table>
<p class="p144 ft19">Se você responder, por exemplo, o número 2 nessa afirmação, está indicando que <span class="ft52">às vezes acontece </span>de você se manter calma em situações tensas. Essa é sua maneira de se comportar.</p>
<p class="p145 ft1">Todas as questões devem ser preenchidas obrigatoriamente.</p>
<p class="p146 ft1">Algumas afirmações podem ser similares, mas nenhuma é exatamente igual.</p>
<p class="p147 ft1">Seja honesta consigo mesma. <nobr>Lembre-se:</nobr> ninguém faz tudo ou sabe fazer tudo corretamente.</p>
<p class="p148 ft1">Você receberá uma análise de seus resultados com breves explicações sobre cada um dos resultados obtidos, que poderão <nobr>auxiliá-la</nobr> na interpretação dos mesmos e na tomada de melhores decisões em seu empreendimento.</p>
<table class="t6" cellpadding="0" cellspacing="0">
<tbody><tr>
    <td colspan="2" class="tr6 td52"><p class="p149 ft1">Afirmação</p></td>
    <td class="tr6 td53"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td53"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td54"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td55"><p class="p150 ft53">1.</p></td>
    <td class="tr22 td56"><p class="p65 ft53">Quando desconheço algo, não me importo em buscar</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr8 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td56"><p class="p65 ft1">informações.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td59"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td60"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr21 td55"><p class="p150 ft1">2.</p></td>
    <td class="tr21 td56"><p class="p65 ft1">As pessoas concordam comigo baseadas em meus</p></td>
    <td class="tr21 td57"><p class="p142 ft1">1</p></td>
    <td class="tr21 td57"><p class="p142 ft1">2</p></td>
    <td class="tr21 td58"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td56"><p class="p65 ft1">argumentos ou estratégias que adoto.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td59"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td60"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td55"><p class="p150 ft53">3.</p></td>
    <td class="tr22 td56"><p class="p65 ft53">Escolho situações em que posso controlar ao máximo os</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td56"><p class="p65 ft19">resultados finais, considerando as possibilidades de êxito ou</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr6 td59"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td60"><p class="p65 ft1">fracasso antes de agir.</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr21 td55"><p class="p150 ft1">4.</p></td>
    <td class="tr21 td56"><p class="p65 ft19">Diante as necessidades do mercado, implanto inovações em</p></td>
    <td class="tr21 td57"><p class="p142 ft1">1</p></td>
    <td class="tr21 td57"><p class="p142 ft1">2</p></td>
    <td class="tr21 td58"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td56"><p class="p65 ft1">meus produtos / serviços, ou amplio área geográfica de</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr1 td59"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td60"><p class="p65 ft1">atuação de minha empresa.</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td55"><p class="p150 ft53">5.</p></td>
    <td class="tr22 td56"><p class="p65 ft53">Reconheço minha responsabilidade nas falhas e eventuais</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr8 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td56"><p class="p65 ft1">prejuízos financeiros e tomo providências para <nobr>corrigi-los.</nobr></p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td59"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td60"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr21 td55"><p class="p150 ft1">6.</p></td>
    <td class="tr21 td56"><p class="p65 ft19">Acredito que posso ser bem sucedida em qualquer atividade</p></td>
    <td class="tr21 td57"><p class="p142 ft1">1</p></td>
    <td class="tr21 td57"><p class="p142 ft1">2</p></td>
    <td class="tr21 td58"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td56"><p class="p65 ft1">que me proponho executar, mesmo sendo algo difícil ou</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr1 td59"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td60"><p class="p65 ft1">desafiador.</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td55"><p class="p150 ft53">7.</p></td>
    <td class="tr22 td56"><p class="p65 ft53">Meu rendimento no trabalho é bastante eficaz, pois faço as</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr8 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td56"><p class="p65 ft19">coisas de acordo com o que foi estabelecido, dando ênfase à</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr1 td59"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td60"><p class="p65 ft1">otimização do tempo.</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td55"><p class="p150 ft53">8.</p></td>
    <td class="tr22 td56"><p class="p65 ft53">Para mim, é mais importante a minha opinião do que a</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td56"><p class="p65 ft19">opinião de outras pessoas sobre o que faço e a maneira como</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr8 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td56"><p class="p65 ft1">eu faço.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td59"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td60"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td55"><p class="p150 ft53">9.</p></td>
    <td class="tr22 td56"><p class="p65 ft53">Executo minhas atividades bem como as atividades dos</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td55"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td56"><p class="p65 ft1">funcionários no dia a dia de minha empresa</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td59"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td60"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
</tbody></table>
</div>
<div id="page_15">


<table class="t7" cellpadding="0" cellspacing="0">
<tbody><tr>
    <td class="tr6 td61"><p class="p149 ft19">10. Adoto, como parâmetro nas negociações, o ditado “quem não</p></td>
    <td class="tr6 td47"><p class="p142 ft1">1</p></td>
    <td class="tr6 td47"><p class="p142 ft1">2</p></td>
    <td class="tr6 td48"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">arrisca, não petisca”.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">11. Busco toda e qualquer informação disponível no mercado</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr1 td63"><p class="p152 ft1">para utilizar em minha empresa.</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">12. Sei de forma clara o que quero alcançar no futuro breve, e</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p77 ft1">estabeleço parâmetros que permitam medir e avaliar o meu</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">desempenho.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft19">13. Faço as coisas <nobr>preocupando-me</nobr> com meus clientes, pois eles</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p152 ft19">sempre têm sempre razão e estão acima de qualquer coisa.</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft19">14. Defino, a cada dia, o percentual de lucro que quero obter em</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr1 td63"><p class="p152 ft1">minha empresa.</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">15. Quando tenho um projeto de grande porte, <nobr>divido-o</nobr> em</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p77 ft1">tarefas mais simples, com prazos estabelecidos</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p152 ft1">antecipadamente.</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">16. Mesmo que eu já esteja obtendo bons resultados em minha</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p77 ft1">empresa, encontro formas de melhorar o que faço (agilidade,</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">custos, qualidade),</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft19">17. Confio em minha capacidade de tomar decisões e solucionar</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr1 td63"><p class="p152 ft1">problemas desafiantes que encontro na rotina empresarial.</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft19">18. Na execução das atividades, minha intuição e criatividade são</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p77 ft1">suficientes para decidir como fazer. Organização e controle</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">são aspectos secundários.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">19. Identifico pessoas influentes e solicito apoio delas para</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p77 ft1">alcançar minhas metas, pois somente assim consigo obter</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">resultados positivos.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr9 td63"><p class="p149 ft1">20. Insisto várias vezes para conseguir o que pretendo.</p></td>
    <td class="tr9 td50"><p class="p142 ft1">1</p></td>
    <td class="tr9 td50"><p class="p142 ft1">2</p></td>
    <td class="tr9 td51"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">21. Aproveito, sem restrições, todas as oportunidades que</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">surgem no mercado, pois elas trazem retorno financeiro.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr21 td62"><p class="p77 ft1">22. Com objetivos comerciais, envio mensagens / brindes aos</p></td>
    <td class="tr21 td57"><p class="p142 ft1">1</p></td>
    <td class="tr21 td57"><p class="p142 ft1">2</p></td>
    <td class="tr21 td58"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">clientes em datas especiais.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft19">23. Faço controles financeiros por meio de registros e utilizo esses</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr1 td63"><p class="p152 ft1">dados para subsidiar as minhas decisões.</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr1 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft19">24. Quando encontro dificuldades na execução de uma atividade,</p></td>
    <td class="tr22 td57"><p class="p48 ft55">&nbsp;</p></td>
    <td class="tr22 td57"><p class="p48 ft55">&nbsp;</p></td>
    <td class="tr22 td58"><p class="p48 ft55">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr6 td63"><p class="p152 ft1"><nobr>permito-me</nobr> aguardar um tempo até que elas se resolvam.</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr21 td62"><p class="p77 ft1">25. Quando necessário, trabalho muito e com afinco para</p></td>
    <td class="tr21 td57"><p class="p142 ft1">1</p></td>
    <td class="tr21 td57"><p class="p142 ft1">2</p></td>
    <td class="tr21 td58"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">completar uma tarefa ou alcançar um objetivo.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr8 td63"><p class="p149 ft1">26. Faço coisas que, na opinião dos outros, são arriscadas.</p></td>
    <td class="tr8 td50"><p class="p142 ft1">1</p></td>
    <td class="tr8 td50"><p class="p142 ft1">2</p></td>
    <td class="tr8 td51"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr21 td62"><p class="p77 ft19">27. Minhas ações diárias são fortemente influenciadas por meus</p></td>
    <td class="tr21 td57"><p class="p142 ft1">1</p></td>
    <td class="tr21 td57"><p class="p142 ft1">2</p></td>
    <td class="tr21 td58"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">objetivos de vida futuros.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">28. Visito feiras e participo de eventos correlatos ao meu</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p77 ft1">empreendimento para conhecer novos produtos / serviços e</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr6 td63"><p class="p152 ft1">fornecedores.</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr21 td62"><p class="p77 ft19">29. Encontro oportunidades de novos negócios quando identifico</p></td>
    <td class="tr21 td57"><p class="p142 ft1">1</p></td>
    <td class="tr21 td57"><p class="p142 ft1">2</p></td>
    <td class="tr21 td58"><p class="p143 ft1">3</p></td>
</tr>
<tr>
    <td class="tr8 td62"><p class="p152 ft1">necessidades ou diagnostico problemas reais.</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr8 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr23 td63"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td50"><p class="p48 ft54">&nbsp;</p></td>
    <td class="tr23 td51"><p class="p48 ft54">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr22 td62"><p class="p77 ft53">30. Realizo vendas para clientes, ainda que não tenha lucro</p></td>
    <td class="tr22 td57"><p class="p142 ft53">1</p></td>
    <td class="tr22 td57"><p class="p142 ft53">2</p></td>
    <td class="tr22 td58"><p class="p143 ft53">3</p></td>
</tr>
<tr>
    <td class="tr9 td62"><p class="p77 ft1">imediato, tendo em vista futuras possibilidades de outros</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td57"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr9 td58"><p class="p48 ft23">&nbsp;</p></td>
</tr>
<tr>
    <td class="tr6 td63"><p class="p152 ft1">negócios com eles.</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td50"><p class="p48 ft23">&nbsp;</p></td>
    <td class="tr6 td51"><p class="p48 ft23">&nbsp;</p></td>
</tr>
</tbody></table>
</div>
<div id="page_16">



<p class="p107 ft19"><span class="ft38">Anexo V - </span>FORMULÁRIO PARA REDAÇÃO DO RELATO (mínimo 40 linhas &ndash; destacado abaixo)</p>
<?php 
$linha = '';
for ($index = 1; $index < 121; $index++) {
    $linha .= $index.'.<br />';
}
echo $linha;
// <p class="p154 ft10">1</p><br />
?>
 
</div>

</div>

<?php /* ?>
<div class="navegacao">
    <a href="#" id="up"><i class="i ir bt-up">up</i></a>
    <a href="#" id="down"><i class="i ir bt-down">down</i></a>
</div>
<?php */ ?>