<?php
$addressEnterprise = $this->enterprise->findAddressEnterprise()->current();
$enterpriseState = $addressEnterprise->findParentState();

$addressEnterprise = $this->enterprise->findAddressEnterprise()->current();
$enterpriseState = $addressEnterprise->findParentState();

$blocoAnterior = ''; 
$criterioAnterior = '';
$qsts = array();
$blocos = array();
$criterios = array();
//Questoes
foreach ($this->questoes as $k => $questao):
    $bloco = $questao->getBloco();
    $criterio = $questao->getCriterio();
    if ($bloco != $blocoAnterior) {
        $qsts[$bloco] = array(
            'BlockName' => Vtx_Util_PsmnAvaliacao::BlocosAvaliacao($bloco), 'Criterions' => array()
        );
    }
    if ($criterio != $criterioAnterior) {
        $qsts[$bloco]['Criterions'][$criterio] = array(
            'CriterionValue' => Vtx_Util_PsmnAvaliacao::CriteriosAvaliacao($bloco, $criterio),
            'Questions' => array()
        );
    }
    $qsts[$bloco]['Criterions'][$criterio]['Questions'][$questao->getId()] = $questao;
    $blocoAnterior = $bloco;
    $criterioAnterior = $criterio;
endforeach;

?>


<a title="Imprimir" style="margin-right: 16px; position: absolute; right: 0" href="#" id="verRelato" onclick="window.print(); return false;"><span>Imprimir</span></a>

<br>

<h1 class="title"><a name="report"></a>Relatório da Candidata</h1>

<?php 
include realpath(dirname(__FILE__) . '/../appraiser/enterprise-scores.phtml');
?>


<fieldset style="width: 100%;">
    <ul class="devolver" style="width: 100%; float:left;  margin: 0; margin: 4px; margin-bottom: 0px">
    <?php $verificador = $score->getFirstNameChecker(); if ($verificador): ?>
       <li style="margin-left: 0; text-align: left; width: 100%; margin-bottom: 4px">
           <div class="list-table-20">
             <label class="label-control">Verificador Estadual</label>
             <span class="label-value"><?php echo $verificador; ?> <b style="font-size: 10px">(<?php echo $score->getLoginChecker(); ?>)</b></span>
           </div>

           <div class="list-table-20">
             <label class="label-control">Bônus</label>
             <span class="label-value">
                 
               <?php
                $qtPf = $score->getQtdePontosFortes(); // isset()
               if ($score->getCheckerStatus() == 'C'): ?>
                   <?php 
                        if (!$qtPf) {
                            echo '-';
                        } elseif ($qtPf >= 8) {
                            echo '20%';
                        }  elseif ($qtPf >= 5) {
                            echo '10%';
                        }
                    ?>
               <?php elseif ($score->getCheckerStatus() == 'I'): ?>
                 Iniciado
               <?php elseif ($score->getCheckerStatus() == 'N'): ?>
                 <Strong>Não iniciado</Strong>
               <?php endif; ?>
             </span>
           </div>

           <div class="list-table-20" style="margin-bottom: 16px;
            margin-right: 5px;
            width: 427px;margin-right: 5px; width: 427px;">
             <label class="label-control">Comentários gerais</label>
             <span class="label-value">
                 <?php echo ($score->getCheckerConclusaoDate())? ("(".$score->getCheckerConclusaoDate() . ")") : ''; ?>
               <?php echo $this->escape($score->getCheckerConclusao()); ?>
             </span>
           </div>
       </li>
        <?php if ($score->getCheckerStatus() == 'C'): ?>
       <li>
        <h2 class="title" style="font: italic bold 18px 'Lato';"><a name="anchor"></a>Comentários</h2>


    <div id="frmAvaliacao" class="avaliacao">


        <div id="avaliacaoRelato"class="inner-content" style="margin-top: 0; padding-top: 0">
        <ul class="root">
    <?php foreach ($qsts as $blockId => $bloco): ?>

          <li class="macro ">
            <span class="title topic" style="display: inline; border: none; visibility: hidden; height: 1px;">
            </span>

            <ul>
            <?php foreach ( $qsts[$blockId]['Criterions'] as $criterioId => $criterio): ?>
              <li class="micro ">
                  <p class="title" style="color: #555; border: none; padding: 0; margin: 0">
                    <b class="topic" style="<?php echo (isset($this->criteriosError[$blockId][$criterioId])? 'background-color: #FCFC8D"' : ''); ?>">
                        <?php echo $bloco['BlockName']; ?> -
                        <?php echo $criterio['CriterionValue']; ?>
                    </b>
                  </p>
                  <p style="font: 14px 'Lato'; color:#999; margin-left: 50px; padding-bottom: 20px">
                    <?php if (isset($this->commentAnswers["$blockId$criterioId"]['Comment'])): ?>
                         <?php echo $this->escape($this->commentAnswers["$blockId$criterioId"]['Comment']); ?>
                     <?php endif; ?>
                  </p>
              </li>
            <?php endforeach; ?>

    <?php endforeach; ?>

          <li class="macro">
            <p class="title">
              <b  style="margin-top: 15px" class="topic">Verificação</b>
            </p>
            
            <ul id="verificacao">
                <li class="micro">
                    <ol class="answers">
                        <?php foreach ($this->questionsAvaliacao as $questionAvaliacao): ?>
                          <li data-weight="20" id="question-1" class="question">
                              <div style="width: 542px;min-height: 20px; <?php echo (isset($this->evaluationQuestionsError[$questionAvaliacao->getId()])? 'background-color: #FCFC8D"' : ''); ?>" class="texto">
                                    <?php echo $questionAvaliacao->getValue(); ?>
                              </div>
                            <?php
                                $checked = (isset($this->respostas[$questionAvaliacao->getId()]) and $this->respostas[$questionAvaliacao->getId()]['Resposta'] == 'F')? true : false;

                                if ($checked) : 
                            ?>
                              <div class="answer-option" style="min-height: 20px; width: 210px; margin-top: 0; margin-bottom: 0; border-right: none">

                                <label class="label-inline radio checked" for="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-F" style="background: none !important; padding: 23px 10px 0; font-weight: bold">
                                  Ponto forte
                                </label>
                                </div>
                              <?php endif; ?>

                                <?php
                                    $checked = (isset($this->respostas[$questionAvaliacao->getId()]) and $this->respostas[$questionAvaliacao->getId()]['Resposta'] == 'M')? true : false;
                                    if ($checked):
                                ?>
                              <div class="answer-option" style="min-height: 20px;width: 210px; border-right: none; margin-top: 0; margin-bottom: 0;">

                                <label class="label-inline radio" for="ansAvaliacao-<?php echo $questionAvaliacao->getId(); ?>-M" style="padding: 23px 10px 0">
                                  Oportunidade de melhoria
                                </label>
                               </div>
                            <?php endif; ?>
                           </li>
                       <?php endforeach; ?>
                    </ol>
                </li>

              </ul>
          </li>

            </ul>
          </li>
    </ul>    
        </div>

    </div>
           
           
       </li>
   <?php endif; ?><?php endif; ?>
    </fieldset>
</ul>













    <!-- Relato -->
    
    <div class="inner-content">
        <ul id="avaliacaoRelato2">
            <li style="float: left; min-height: 100px; width: auto; height: 100px; overflow: hidden;  border-right: 3px solid #F5F6F7;">
                <?php
                    for ($index = 1; $index < 1000; $index++) {
                        echo '<span style="line-height: 22px;  text-align: right; border-bottom: 1px solid #F5F6F7;  font: italic 14px/22px \'Lato\'; color: #ACACAC; width: 35px; display:block;">' . $index . ' &nbsp; <br></span>';
                    }
                ?>
            </li>
            <li style="padding-left: 10px; width: 730px; float: left; font: 14px/23px 'Lato'; color: rgb(237, 124, 76);">
                <strong><?php echo $this->escape($this->report->getTitle()); ?></strong><br>   
                <?php echo str_replace('&lt;br /&gt;', '<br>', $this->escape(nl2br($this->report->getReport()))); ?>
            </li>
        </ul>
<hr style="clear:both;opacity:0">
    </div>
</form>
<?php $this->headScript()->captureStart() ?>
    $(document).ready(function() {
        setTimeout(function(){
            cols = $('#avaliacaoRelato2 li');
            cols.eq(0).height(cols.eq(1).height()+207);
            $('#menu-top, #profile').hide();
            $('div.container12').css('margin-top', -97);
        }, 100);
    });
<?php $this->headScript()->captureEnd() ?>