<table class="table">
  <caption></caption>
  <thead>
    <tr>
        <th style="height: 100px">Classificada</th>
      <th>Empresa</th>
      <th>UF</th>
      <th>RAA</th>
      <th>Relat.<br>Interno</th>
      <th>Verificar <br>Questionário <br>de Auto Aval.</br> Negócios</th>
      <th>Verificar <br>Questionário <br>de Visita</th>
      <th>Verificar <br>Critério <br>de Avaliação</th>
      <th>Gerar <br>Relatório <br>de Avaliação</th>
      <th>Status</th> 
      <th>Enviar <br>ao Gestor</th>
      
    </tr>
  </thead>
<?php
if (count($this->getAllEnterprise) >= 1):
?>
  <tbody>
 
<?php
$userIdLogged = Zend_Auth::getInstance()->getIdentity()->getUserId();
  foreach ($this->getAllEnterprise as $index => $enterprise) :
 
    
    $raa = $enterprise->getDevolutivePath();
    $scoreGestao = '';//$enterprise->getProgressGestao();
    $fantasyName = $enterprise->getFantasyName();
    $socialName = $enterprise->getSocialName();
    $avaliacaoStatus = $enterprise->getCheckerStatus();
    
    

    $CNPJ = trim($enterprise->getCnpj());
    $CPF = trim($enterprise->getCpfUser());
    $enterpriseType = $CPF; //($enterpriseTypeId == '1')?$CNPJ:$CPF;
    $UF = trim($enterprise->getUf());

    $survey = $this->baseUrl('/management/verificacao/index/enterprise-id-key/' 
        . $enterprise->getIdKey());
    
    $verificarCriterio = $this->baseUrl('/management/verificacao/criterioavaliacao/enterprise-id-key/' 
        . $enterprise->getIdKey());
    
    $verificarquestionarioNegocio = $this->baseUrl('/management/verificacao/questionarionegocio/enterprise-id-key/' 
        . $enterprise->getIdKey(). '/block/'. Zend_Registry::get('configDb')->qstn->currentBlockIdNegocios);
    
    $GerarRelatorio = $this->baseUrl();
    $EnviarGestor = $this->baseUrl();
    
?>
    <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="<?php echo $enterprise->getIdKey(); ?>">
      <td>
          <dl style="text-align: left; margin-left: 5px">
          <dt title="<?php echo $fantasyName; ?>"><b><?php echo (($enterprise->getNameUser() != '') ? substr($enterprise->getNameUser(), 0, 60) : '--'); ?></b></dt>
          <dd class="identity" title="<?php echo $enterpriseType; ?>"><?php echo $enterprise->getCpfUser(); ?></dd>
        </dl>

      </td>
      
        <td style="width: 300px; height: 45px;" title="<?php echo $socialName; ?>">
          <dl style="text-align: left; margin-left: 5px">
            <dt><b><?php echo (($fantasyName != '') ? substr($fantasyName, 0, 60) : '--'); ?></b></dt>
            <dd class="identity"><?php echo $CNPJ; ?></dd>
          </dl>
        </td>
        
      <td class="middle"><i><?php echo $UF; ?></i></td>
      <td class="middle">
        <dl>
          <dt>
            <a href="<?php echo $raa; ?>" title="Baixar RAA" class="download-raa" target="blank">Baixar RAA</a>
          </dt>
        </dl>
      </td>
      <td class="middle">
        <dl>
          <dt>
            <a href="<?php echo $this->baseUrl("management/verificacao/report/enterprise-id-key/{$enterprise->getIdKey()}"); ?>#report" title="Relatório Interno" class="download-raa" target="blank">Interno</a>
          </dt>
        </dl>
      </td>
            <td class="middle">
        <dl>
            <dt>
                <a href="<?php echo $verificarquestionarioNegocio; ?>" title="Verificar Questionário de Negócios" 
                   class="answer-survey" >Verificar Questionário de Negócios
                </a>
            </dt>
        </dl>
      </td>
      <td class="middle">
        <dl>
            <dt>
                <a href="<?php echo $survey; ?>" title="Verificar Questionário de Visita" 
                   class="answer-survey" >Verificar Questionário de Visita</a>
            </dt>
        </dl>
      </td>

      <td class="middle">
        <dl>
            <dt>
                <a href="<?php echo $verificarCriterio; ?>" title="Critério de Avaliação" 
                   class="answer-survey" >Critério de Avaliação</a>
            </dt>
        </dl>
      </td>

      <td class="middle">
        <dl>
            <dt>
                <a href="<?php echo $GerarRelatorio; ?>" title="Gerar Relatório de Avaliação" 
                   class="answer-survey" >Gerar relatório de Avaliação</a>
            </dt>
        </dl>
      </td>      
      <td style="padding:5px;">
          <?php
                  
            echo Vtx_Util_PsmnAvaliacao::statusReport($avaliacaoStatus);
          ?>
      </td>
      
      <td class="middle">
        <dl>
            <dt>
            <?php
            if($avaliacaoStatus != "N" && $avaliacaoStatus != "I"):
            ?>
                <a href="<?php echo $EnviarGestor; ?>" title="Enviar ao Gestor" 
                   class="answer-survey" >Enviar ao Gestor</a>
             <?php endif; ?>      
            </dt>
        </dl>
      </td>
      
    </tr>
<?php endforeach; ?>
  </tbody>
<?php endif; ?>
</table>