
<h1 class="title">Arquivos</h1>

<ul id="arquivos">
    <li>
        <a href="/files/codigo_etica_revisado_v1_psmn_2015.docx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Código de Ética PSMN - 2015</b>
        </a>
    </li>
    <?php /* ?>
    <?php */ ?>

    <li>
        <a href="/files/reuniao_gestores_apostila_psmn_2015.pdf" target="_blank" style="background-image: url(/img/icon-pdf.png); background-repeat: no-repeat;">
            <b>Reunião de Gestores PSMN - 2015</b>
            Compartilhar as melhores práticas de gestão do Prêmio SEBRAE Mulher de Negócios.</a>
    </li>

    <li>
        <a href="/files/manual_gestor_revisado_v2_2015.doc" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Manual do Gestor do PSMN - 2015</b>
            Documento contendo orientações sobre os processos do Prêmio SEBRAE Mulher de Negócios.</a>
    </li>
    <li>
        <a href="/files/termo_compromisso_adesao_v1_psmn_2015.docx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Termo de Compromisso e Adesão ao PSMN - 2015</b>
            Documento contendo o Termo de Compromisso e Adesão ao Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>

    <li>

        <a href="/files/tutorial_aplicacao_sistema_PSMN_2015.pptx" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Tutorial de Aplicação do Sistema – PSMN 2015</b>
            Documento contendo o Tutorial de Aplicação do Sistema Prêmio SEBRAE Mulher de Negócios para o ciclo de 2015.</a>
    </li>


</ul>
