
<h1 class="title">Arquivos</h1>

<ul id="arquivos">
    <li><a href="/files/psmn2014-CapacitacaoGestoresPSMN2014.pptx" target="_blank" style="background-image: url(/img/icon-ppt.png); background-repeat: no-repeat;">
        <b>Capacitação gestores PSMN:</b>
        Arquivo Capacitação gestores PSMN 2014, 26 e 27 de fevereiro de 2014.</a>
    </li>
    <li>
            <a href="/files/psmn2014-CapacitacaoNovosGestoresPSMN2014.pptx" target="_blank" style="background-image: url(/img/icon-ppt.png); background-repeat: no-repeat;">
            <b>Capacitação de NOVOS Gestores PSMN</b>
            Slides apresentados na Capacitação de Novos Gestores<?php /*?>, realizada 24 de fevereiro de 2014, em Brasília<?php */ ?></a>
    </li>
    <li><a href="/files/psmn2014-ManualDoGestorPSMN2014.pdf" target="_blank" style="background-image: url(/img/icon-pdf.png); background-repeat: no-repeat;">
                <b> Manual do Gestor do PSMN - 2014</b>
        Documento contendo orientações sobre os processos do Prêmio SEBRAE Mulher de Negócio</a>
    </li>
    <li>
            <a href="/files/psmn2013-manual-estadual.doc" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
                <b>Manual da Comissão Julgadora do PSMN - 2013</b>
        Modelo de Manual da Comissão Julgadora do Prêmio SEBRAE Mulher de Negócios 2013</a>
    </li>
    <?php /* ?>
    <?php */ ?>

    <li><a href="/files/psmn2014-ManualDaBancaAvaliadoraPSMN2014.pdf" target="_blank" style="background-image: url(/img/icon-pdf.png); background-repeat: no-repeat;">
        <b>Manual da banca avaliadora PSMN - 2014</b>
        Este manual contém todas as informações necessárias para que você possa avaliar/verificar as candidatas do maior reconhecimento às mulheres empreendedoras: o Prêmio SEBRAE Mulher de Negócios (PSMN).</a>
    </li>
    <li>
        <a href="/files/psmn2013-capacitacao-banca-avaliadora-novos-e-hibrida.pptx" target="_blank" style="background-image: url(/img/icon-ppt.png); background-repeat: no-repeat;">
        <b>Capacitação da Banca Avaliadora</b>
        Capacitar os participantes para a análise de relatos e para a visita de verificação, evidenciando os requisitos solicitados nos Critérios de Avaliação do Prêmio SEBRAE Mulher de Negócios – Ciclo 2014.</a>
    </li>
    <?php /* ?>
    <?php */ ?>

    <li>
        <a href="/files/psmn2014-WorkshopBoasPraticasPSMN2014" target="_blank" style="background-image: url(/img/icon-ppt.png); background-repeat: no-repeat;">
        <b>Workshop de Boas Práticas</b>
        Compartilhar as melhores práticas de gestão do Prêmio SEBRAE Mulher de Negócios.</a>
    </li>

    <li>
        <a href="/files/psmn2014-manual-estadual.doc" target="_blank" style="background-image: url(/img/icon-doc.png); background-repeat: no-repeat;">
            <b>Manual da Comissão Julgadora do PSMN - 2014</b>
            Modelo de Manual da Comissão Julgadora do Prêmio SEBRAE Mulher de Negócios 2014
        </a>
    </li>
</ul>
