<div class="table-menu header">
      <hgroup><a name="lista"></a><h2><?php echo $titulo; ?>

          </h2>
      </hgroup>
    <?php if ($buttonExport): ?>
            <div class="nav tools">
              <p>Ferramentas:</p>
              <ul>
                <li><a href="<?php echo $this->baseUrl('management/enterprise/report-regional/?' . $this->urlParaGerarCsv); ?>" target="_blank" title="Exportar empresas"><span>Exportar<i> empresas</i></span></a></li>
              </ul>
            </div>
    <?php endif; ?>
</div>
<div class="table-container <?php echo ($fluid  ? 'fluid' : ''); ?>">
<table class="table">
  <thead>
    <tr>
      <th>Estado</th>
      <th style="width: 122px">Região</th>
      <th>Escritório<br>Regional</th>
      <th>Inscritas</th>
      <th>Candidatas</th>
      <th>Verificadas</th>
      <th>Vencedora <br> Bronze</th>
      <th>Vencedora <br> Prata</th>
      <th>Vencedora <br> Ouro</th>
    </tr>
  </thead>

<?php if (count($this->dataReport) >= 1): ?>
  <tbody>
    <?php foreach ($this->dataReport as $index => $dataRow): ?>
        <tr class="<?php echo ((($index % 2) == 0) ? 'odd' : 'even'); ?>" data-idkey="">
            <td><span><?php echo $dataRow->getUf(); ?></span></td>
            <td><span><?php echo $dataRow->getRegiao(); ?></span></td>
            <td><span class="left"><?php echo $dataRow->getRegionalDescription(); ?></span></td>
            <td class="middle"><span><?php echo $dataRow->getInscritas(); ?></span></td>
            <td class="middle"><span><?php echo $dataRow->getCandidatas(); ?></span></td>
            <td class="middle"><span>0</span></td>
            <td class="middle"><span>0</span></td>
            <td class="middle"><span>0</span></td>
            <td class="middle"><span>0</span></td>
        </tr>
<?php
  endforeach;
?>
  </tbody>
<?php
endif;
?>
</table>
</div>